remote_theme: just-the-docs/just-the-docs
title: EalEx Documentation
aux_links:
  "View on GitHub":
    - "//github.com/ezylang/evalex-core"
footer_content: "Copyright &copy; 2012-2022 Udo Klimaschewski"
