remote_theme: just-the-docs/just-the-docs
title: EzyLang GitHub pages playground
aux_links:
  "View on GitHub":
    - "//github.com/ezylang/pages-playground"
footer_content: "Copyright &copy; 2012-2022 Udo Klimaschewski"
